Typo

diff --git a/eng/pipelines/pr.yaml b/eng/pipelines/pr.yaml
--- a/eng/pipelines/pr.yaml
+++ b/eng/pipelines/pr.yaml
@@ -40,9 +40,12 @@ jobs:
 
       - script: ls ./packages
       - script: |
-          corePkg="$(find ./packages -type f -iname "autorest-core-*.tgz" )"
-          modelerfourPkg="$(find ./packages -type f -iname "autorest-modelerfour-*.tgz" )"
+          corePkg="$(find $(Pipeline.Workspace)/packages -type f -iname "autorest-core-*.tgz" )"
+          modelerfourPkg="$(find $(Pipeline.Workspace)/packages -type f -iname "autorest-modelerfour-*.tgz" )"
 
+          [ -z "$corePkg" ] && echo "Error: Couldn't find autorest core package" && exit 1
+          [ -z "$modelerfourPkg" ] && echo "Error: Couldn't find autorest modelerfour package" && exit 1
+          
           echo "Found core package $corePkg"
           echo "Found modelerfour package $modelerfourPkg"
 
